image:
  name: docker:git

services:
  - docker:18.09.7-dind

stages:
  - deployment

deployment_job:
  stage: deployment
  only:
    refs:
      - master
  before_script:
    - apk update && apk add --no-cache build-base cargo gcc libffi-dev libressl-dev musl-dev openssl-dev python3 python3-dev py3-pip
  script:
    - pip3 install wheel
    - pip3 install -r requirements.txt
    - python3 setup.py bdist_wheel
    - TWINE_PASSWORD=${CI_PASSWORD} TWINE_USERNAME=${CI_USERNAME} python3 -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*